### PR TITLE
Raise better error when mjml binary is not found

### LINKED ISSUE #12: Improve error message when mjml is not installed
In a server I've got an issue where mails was not sent anymore. 

We've got the following error, because `mjml` was not installed (it was before):
```
ActionView::Template::Error
No such file or directory - 
```

I think [`#extract_executable_version`](https://github.com/kolybasov/mjml-ruby/blob/master/lib/mjml.rb#L43) method needs to catch `Errno::ENOENT` exception, or something like that.

It may help a lot for debug.

In our case, on each deploys packages are installed. But some server changes made that `yarn install` doesn't installed `mjml`.  
For me the main issue here was that the error message came from ActionMailer and not MJML gem.

### PR DESCRIPTION
**Pull request by nicolas-brousse**
Closes #12

### CODE REVIEW

**Comment by nicolas-brousse** [comment]
@kolybasov let me know if some part of my PR is not okay for you.

**Comment by m-basov** [comment]
@nicolas-brousse looks great. Nice job! 👍 I will add you as collaborator in case you are interested to support this project. I am not into Ruby anymore but seems people still use it so it will be great if it will continue to work :)

**Comment by m-basov** [comment]
@nicolas-brousse v0.3.3 published to RubyGems https://github.com/kolybasov/mjml-ruby/releases/tag/v0.3.3

**Comment by nicolas-brousse** [comment]
Thanks for it and for the invitation :)

**Pull request merged**
