### PR TITLE
Handle slim and haml templates

### PR DESCRIPTION
**Pull request by vddgil**
Added the ability to use .mjmlslim and .mjmlhaml templates

### CODE REVIEW

**Comment by m-basov** [comment]
@vddgil hi! Thanks for your PR! Will it works just with new extension or I should configure something to use slim, haml or erb handler? I am asking about this string:

``` ruby
def initialize(base_handler = :erb)
  @base_handler = base_handler
end
```

**Comment by vddgil** [comment]
I will just work with the new extension
- .mjml if you want erb (like before)
- .mjmlslim if you want slim
- .mjmlhaml if you want haml

Nothing to configure

**Comment by m-basov** [comment]
@vddgil cool. I am thinking about another way to detect handler. Example:
- _.mjml / .mjml.erb_ – Erubis
- _.mjml.haml_ – Haml
- _.mjml.slim_ – Slim

Guess it's more clear for IDE's/Editor's than creating new extension. What you think?

**Comment by vddgil** [comment]
Yes, that was my first solution. But it appears that rails doesn't support chaining multiple handlers for the views 👎 . So I came up with those weird extensions ...

See this article: http://www.mcdonaldland.info/2014/01/14/chaining-rails-template-view-handlers/

**Comment by m-basov** [comment]
@vddgil I am sure that saw a way to check extension of processed file. Let me find it.

**Comment by vddgil** [comment]
If you find a way to handle a .html.mjml.slim / haml view, I will be really happy :)
Because that's the problem, as soon as you have two handlers after the .html, rails is suddenly not able to find your view :(

**Comment by m-basov** [comment]
@vddgil you are right. Rails don't support more than 2 extensions for templates because of first one is response format and second one is template handler. So I will merge your PR and will add documentation later. Thanks a lot!

**Pull request merged**
